CFLAGS=-pipe       -fexceptions      -fno-math-errno      -fno-strict-aliasing      -fsigned-char      -g      -pthread      -mtune=prescott      -march=prescott      -mmmx      -msse      -msse2        -msse3      -mfpmath=both        -w        -O3


libndofdev.a:	ndofdev.o
		$(AR) -r $@ $< 

clean:
		-rm -f *.a *.o

